
USE DATABASE RUNNING_TELCO;
USE SCHEMA ORCHESTRATION;

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_LOAD_STG_CUSTOMERS
  WAREHOUSE = WH_TRANSFORM
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
  COMMENT = 'Root: RAW_CUSTOMERS -> STG_CUSTOMERS, daily 06:00 UTC'
  AS
  CALL STAGING.SP_LOAD_STG_CUSTOMERS();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_MERGE_DIM_CUSTOMER
  WAREHOUSE = WH_TRANSFORM
  AFTER ORCHESTRATION.TASK_LOAD_STG_CUSTOMERS
  WHEN SYSTEM$STREAM_HAS_DATA('RUNNING_TELCO.STAGING.STRM_CUSTOMERS')
  AS
  CALL CURATED.SP_MERGE_DIM_CUSTOMER();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_LOAD_STG_PLANS
  WAREHOUSE = WH_TRANSFORM
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
  AS
  CALL STAGING.SP_LOAD_STG_PLANS();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_MERGE_DIM_PLAN
  WAREHOUSE = WH_TRANSFORM
  AFTER ORCHESTRATION.TASK_LOAD_STG_PLANS
  WHEN SYSTEM$STREAM_HAS_DATA('RUNNING_TELCO.STAGING.STRM_PLANS')
  AS
  CALL CURATED.SP_MERGE_DIM_PLAN();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_LOAD_STG_DEVICES
  WAREHOUSE = WH_TRANSFORM
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
  AS
  CALL STAGING.SP_LOAD_STG_DEVICES();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_MERGE_DIM_DEVICE
  WAREHOUSE = WH_TRANSFORM
  AFTER ORCHESTRATION.TASK_LOAD_STG_DEVICES
  WHEN SYSTEM$STREAM_HAS_DATA('RUNNING_TELCO.STAGING.STRM_DEVICES')
  AS
  CALL CURATED.SP_MERGE_DIM_DEVICE();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_LOAD_STG_TOWERS
  WAREHOUSE = WH_TRANSFORM
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
  AS
  CALL STAGING.SP_LOAD_STG_TOWERS();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_MERGE_DIM_TOWER
  WAREHOUSE = WH_TRANSFORM
  AFTER ORCHESTRATION.TASK_LOAD_STG_TOWERS
  WHEN SYSTEM$STREAM_HAS_DATA('RUNNING_TELCO.STAGING.STRM_TOWERS')
  AS
  CALL CURATED.SP_MERGE_DIM_TOWER();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_LOAD_STG_BILLING
  WAREHOUSE = WH_TRANSFORM
  SCHEDULE = 'USING CRON 0 7 * * * UTC'
  COMMENT = 'Runs after billing run typically completes upstream (07:00 UTC)'
  AS
  CALL STAGING.SP_LOAD_STG_BILLING();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_MERGE_FACT_BILLING
  WAREHOUSE = WH_TRANSFORM
  AFTER ORCHESTRATION.TASK_LOAD_STG_BILLING
  WHEN SYSTEM$STREAM_HAS_DATA('RUNNING_TELCO.STAGING.STRM_BILLING')
  AS
  CALL CURATED.SP_MERGE_FACT_BILLING();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_LOAD_STG_PAYMENTS
  WAREHOUSE = WH_TRANSFORM
  SCHEDULE = 'USING CRON 0 7 * * * UTC'
  AS
  CALL STAGING.SP_LOAD_STG_PAYMENTS();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_MERGE_FACT_PAYMENTS
  WAREHOUSE = WH_TRANSFORM
  AFTER ORCHESTRATION.TASK_LOAD_STG_PAYMENTS
  WHEN SYSTEM$STREAM_HAS_DATA('RUNNING_TELCO.STAGING.STRM_PAYMENTS')
  AS
  CALL CURATED.SP_MERGE_FACT_PAYMENTS();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_LOAD_STG_SUPPORT_TICKETS
  WAREHOUSE = WH_TRANSFORM
  SCHEDULE = 'USING CRON 0 6 * * * UTC'
  AS
  CALL STAGING.SP_LOAD_STG_SUPPORT_TICKETS();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_MERGE_FACT_SUPPORT_TICKETS
  WAREHOUSE = WH_TRANSFORM
  AFTER ORCHESTRATION.TASK_LOAD_STG_SUPPORT_TICKETS
  WHEN SYSTEM$STREAM_HAS_DATA('RUNNING_TELCO.STAGING.STRM_SUPPORT_TICKETS')
  AS
  CALL CURATED.SP_MERGE_FACT_SUPPORT_TICKETS();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_LOAD_STG_CDR
  WAREHOUSE = WH_TRANSFORM
  SCHEDULE = 'USING CRON 0 * * * * UTC'
  COMMENT = 'Root: RAW_CDR -> STG_CDR, hourly'
  AS
  CALL STAGING.SP_LOAD_STG_CDR();

CREATE TASK IF NOT EXISTS ORCHESTRATION.TASK_MERGE_FACT_CDR_USAGE
  WAREHOUSE = WH_TRANSFORM
  AFTER ORCHESTRATION.TASK_LOAD_STG_CDR
  WHEN SYSTEM$STREAM_HAS_DATA('RUNNING_TELCO.STAGING.STRM_CDR')
  AS
  CALL CURATED.SP_MERGE_FACT_CDR_USAGE();

ALTER TASK ORCHESTRATION.TASK_MERGE_DIM_CUSTOMER         RESUME;
ALTER TASK ORCHESTRATION.TASK_MERGE_DIM_PLAN             RESUME;
ALTER TASK ORCHESTRATION.TASK_MERGE_DIM_DEVICE           RESUME;
ALTER TASK ORCHESTRATION.TASK_MERGE_DIM_TOWER             RESUME;
ALTER TASK ORCHESTRATION.TASK_MERGE_FACT_BILLING          RESUME;
ALTER TASK ORCHESTRATION.TASK_MERGE_FACT_PAYMENTS         RESUME;
ALTER TASK ORCHESTRATION.TASK_MERGE_FACT_SUPPORT_TICKETS  RESUME;
ALTER TASK ORCHESTRATION.TASK_MERGE_FACT_CDR_USAGE        RESUME;

ALTER TASK ORCHESTRATION.TASK_LOAD_STG_CUSTOMERS          RESUME;
ALTER TASK ORCHESTRATION.TASK_LOAD_STG_PLANS              RESUME;
ALTER TASK ORCHESTRATION.TASK_LOAD_STG_DEVICES            RESUME;
ALTER TASK ORCHESTRATION.TASK_LOAD_STG_TOWERS             RESUME;
ALTER TASK ORCHESTRATION.TASK_LOAD_STG_BILLING            RESUME;
ALTER TASK ORCHESTRATION.TASK_LOAD_STG_PAYMENTS           RESUME;
ALTER TASK ORCHESTRATION.TASK_LOAD_STG_SUPPORT_TICKETS    RESUME;
ALTER TASK ORCHESTRATION.TASK_LOAD_STG_CDR                RESUME;

