
USE DATABASE RUNNING_TELCO;
USE SCHEMA GOVERNANCE;
USE ROLE R_DATA_GOVERNANCE;

CREATE TAG IF NOT EXISTS GOVERNANCE.DATA_CLASSIFICATION
  ALLOWED_VALUES 'PII', 'FINANCIAL', 'CONFIDENTIAL', 'PUBLIC', 'INTERNAL'
  COMMENT = 'Top level sensitivity classification for a column';

CREATE TAG IF NOT EXISTS GOVERNANCE.PII_CATEGORY
  ALLOWED_VALUES 'NAME', 'NATIONAL_ID', 'CONTACT_INFO', 'ADDRESS', 'DOB', 'PAYMENT_CARD', 'NONE'
  COMMENT = 'Sub-category of PII for regulatory reporting (GDPR/CCPA style inventories)';

CREATE TAG IF NOT EXISTS GOVERNANCE.COST_CENTER
  COMMENT = 'Free-text cost center tag applied at warehouse/database level for chargeback reporting';

ALTER TABLE CURATED.DIM_CUSTOMER MODIFY COLUMN first_name     SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII', GOVERNANCE.PII_CATEGORY = 'NAME';
ALTER TABLE CURATED.DIM_CUSTOMER MODIFY COLUMN last_name      SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII', GOVERNANCE.PII_CATEGORY = 'NAME';
ALTER TABLE CURATED.DIM_CUSTOMER MODIFY COLUMN date_of_birth  SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII', GOVERNANCE.PII_CATEGORY = 'DOB';
ALTER TABLE CURATED.DIM_CUSTOMER MODIFY COLUMN national_id    SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'CONFIDENTIAL', GOVERNANCE.PII_CATEGORY = 'NATIONAL_ID';
ALTER TABLE CURATED.DIM_CUSTOMER MODIFY COLUMN email          SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII', GOVERNANCE.PII_CATEGORY = 'CONTACT_INFO';
ALTER TABLE CURATED.DIM_CUSTOMER MODIFY COLUMN phone_number   SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII', GOVERNANCE.PII_CATEGORY = 'CONTACT_INFO';
ALTER TABLE CURATED.DIM_CUSTOMER MODIFY COLUMN address_line1  SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII', GOVERNANCE.PII_CATEGORY = 'ADDRESS';
ALTER TABLE CURATED.DIM_CUSTOMER MODIFY COLUMN credit_score   SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'FINANCIAL', GOVERNANCE.PII_CATEGORY = 'NONE';

ALTER TABLE CURATED.FACT_PAYMENTS MODIFY COLUMN card_last4 SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'FINANCIAL', GOVERNANCE.PII_CATEGORY = 'PAYMENT_CARD';
ALTER TABLE CURATED.FACT_PAYMENTS MODIFY COLUMN amount     SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'FINANCIAL', GOVERNANCE.PII_CATEGORY = 'NONE';

ALTER TABLE CURATED.FACT_CDR_USAGE MODIFY COLUMN origin_number      SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII', GOVERNANCE.PII_CATEGORY = 'CONTACT_INFO';
ALTER TABLE CURATED.FACT_CDR_USAGE MODIFY COLUMN destination_number SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII', GOVERNANCE.PII_CATEGORY = 'CONTACT_INFO';

ALTER TABLE CURATED.FACT_BILLING MODIFY COLUMN total_amount   SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'FINANCIAL';
ALTER TABLE CURATED.FACT_BILLING MODIFY COLUMN usage_charges  SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'FINANCIAL';

ALTER WAREHOUSE WH_TRANSFORM SET TAG GOVERNANCE.COST_CENTER = 'DATA_ENGINEERING';
ALTER WAREHOUSE WH_BI        SET TAG GOVERNANCE.COST_CENTER = 'ANALYTICS';
ALTER WAREHOUSE WH_INGEST    SET TAG GOVERNANCE.COST_CENTER = 'DATA_ENGINEERING';

