
USE DATABASE RUNNING_TELCO;
USE SCHEMA GOVERNANCE;
USE ROLE R_DATA_GOVERNANCE;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MP_MASK_NATIONAL_ID AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('R_COMPLIANCE_OFFICER', 'R_TELECOM_ADMIN') THEN val
    ELSE 'XXX-XX-' || RIGHT(val, 4)
  END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MP_MASK_EMAIL AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('R_COMPLIANCE_OFFICER', 'R_TELECOM_ADMIN') THEN val
    WHEN CURRENT_ROLE() IN ('R_ANALYST_GLOBAL', 'R_ANALYST_NORTH', 'R_ANALYST_SOUTH')
      THEN CONCAT('***@', SPLIT_PART(val, '@', 2))
    ELSE '***MASKED***'
  END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MP_MASK_PHONE AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('R_COMPLIANCE_OFFICER', 'R_TELECOM_ADMIN') THEN val
    ELSE CONCAT(LEFT(val, 3), '-XXX-', RIGHT(val, 2))
  END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MP_MASK_ADDRESS AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('R_COMPLIANCE_OFFICER', 'R_TELECOM_ADMIN') THEN val
    ELSE '***ADDRESS REDACTED***'
  END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MP_MASK_DOB AS (val DATE) RETURNS DATE ->
  CASE
    WHEN CURRENT_ROLE() IN ('R_COMPLIANCE_OFFICER', 'R_TELECOM_ADMIN') THEN val
    WHEN CURRENT_ROLE() IN ('R_ANALYST_GLOBAL', 'R_ANALYST_NORTH', 'R_ANALYST_SOUTH')
      THEN DATE_FROM_PARTS(YEAR(val), 1, 1)
    ELSE NULL
  END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MP_MASK_CARD AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('R_COMPLIANCE_OFFICER', 'R_TELECOM_ADMIN') THEN val
    ELSE '**' || RIGHT(val, 2)
  END;

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MP_ROUND_CURRENCY AS (val NUMBER(12,2)) RETURNS NUMBER(12,2) ->
  CASE
    WHEN CURRENT_ROLE() IN ('R_COMPLIANCE_OFFICER', 'R_TELECOM_ADMIN', 'R_DATA_ENGINEER') THEN val
    ELSE ROUND(val, -1)
  END;

ALTER TABLE CURATED.DIM_CUSTOMER MODIFY COLUMN national_id   SET MASKING POLICY GOVERNANCE.MP_MASK_NATIONAL_ID;
ALTER TABLE CURATED.DIM_CUSTOMER MODIFY COLUMN email         SET MASKING POLICY GOVERNANCE.MP_MASK_EMAIL;
ALTER TABLE CURATED.DIM_CUSTOMER MODIFY COLUMN phone_number  SET MASKING POLICY GOVERNANCE.MP_MASK_PHONE;
ALTER TABLE CURATED.DIM_CUSTOMER MODIFY COLUMN address_line1 SET MASKING POLICY GOVERNANCE.MP_MASK_ADDRESS;
ALTER TABLE CURATED.DIM_CUSTOMER MODIFY COLUMN date_of_birth SET MASKING POLICY GOVERNANCE.MP_MASK_DOB;

ALTER TABLE CURATED.FACT_PAYMENTS MODIFY COLUMN card_last4 SET MASKING POLICY GOVERNANCE.MP_MASK_CARD;

ALTER TABLE CURATED.FACT_CDR_USAGE MODIFY COLUMN origin_number      SET MASKING POLICY GOVERNANCE.MP_MASK_PHONE;
ALTER TABLE CURATED.FACT_CDR_USAGE MODIFY COLUMN destination_number SET MASKING POLICY GOVERNANCE.MP_MASK_PHONE;

