
USE DATABASE RUNNING_TELCO;
USE SCHEMA GOVERNANCE;
USE ROLE R_DATA_GOVERNANCE;

CREATE TABLE IF NOT EXISTS GOVERNANCE.ROLE_REGION_MAP (
    role_name     VARCHAR(100) NOT NULL,
    region        VARCHAR(50)  NOT NULL,
    CONSTRAINT PK_ROLE_REGION_MAP PRIMARY KEY (role_name, region)
)
COMMENT = 'Drives ROW ACCESS POLICY RAP_REGION_RESTRICT - which role sees which region(s)';

INSERT INTO GOVERNANCE.ROLE_REGION_MAP (role_name, region) VALUES
    ('R_ANALYST_NORTH', 'NORTH'),
    ('R_ANALYST_SOUTH', 'SOUTH');

CREATE OR REPLACE ROW ACCESS POLICY GOVERNANCE.RAP_REGION_RESTRICT
  AS (region_col STRING) RETURNS BOOLEAN ->
  CURRENT_ROLE() IN ('R_TELECOM_ADMIN', 'R_DATA_ENGINEER', 'R_DATA_GOVERNANCE',
                      'R_ANALYST_GLOBAL', 'R_COMPLIANCE_OFFICER')
  OR EXISTS (
      SELECT 1 FROM GOVERNANCE.ROLE_REGION_MAP m
      WHERE m.role_name = CURRENT_ROLE()
        AND m.region = region_col
  );

ALTER TABLE CURATED.DIM_CUSTOMER
  ADD ROW ACCESS POLICY GOVERNANCE.RAP_REGION_RESTRICT ON (region);

ALTER TABLE CURATED.FACT_CDR_USAGE
  ADD ROW ACCESS POLICY GOVERNANCE.RAP_REGION_RESTRICT ON (region);

ALTER TABLE CURATED.DIM_TOWER
  ADD ROW ACCESS POLICY GOVERNANCE.RAP_REGION_RESTRICT ON (region);

GRANT SELECT ON ALL TABLES IN SCHEMA CURATED TO ROLE R_ANALYST_NORTH;
GRANT SELECT ON ALL TABLES IN SCHEMA CURATED TO ROLE R_ANALYST_SOUTH;
GRANT SELECT ON ALL TABLES IN SCHEMA CURATED TO ROLE R_ANALYST_GLOBAL;
GRANT SELECT ON ALL TABLES IN SCHEMA CURATED TO ROLE R_COMPLIANCE_OFFICER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA CURATED TO ROLE R_ANALYST_NORTH;
GRANT SELECT ON ALL VIEWS  IN SCHEMA CURATED TO ROLE R_ANALYST_SOUTH;
GRANT SELECT ON ALL VIEWS  IN SCHEMA CURATED TO ROLE R_ANALYST_GLOBAL;
GRANT SELECT ON ALL VIEWS  IN SCHEMA CURATED TO ROLE R_COMPLIANCE_OFFICER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA CURATED TO ROLE R_ANALYST_GLOBAL;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA CURATED TO ROLE R_ANALYST_GLOBAL;

