
/* ==========================================================================
   WAREHOUSES
   ========================================================================== */
CREATE WAREHOUSE IF NOT EXISTS WH_INGEST
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Used by Snowpipe / COPY INTO / staging loads';

CREATE WAREHOUSE IF NOT EXISTS WH_TRANSFORM
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Used by tasks/procedures for STAGING -> CURATED transforms';

CREATE WAREHOUSE IF NOT EXISTS WH_BI
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 300
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Used by BI/analysts/reader accounts querying CURATED/SHARE_OUT';

/* ==========================================================================
   FUNCTIONAL ROLES (RBAC)
   ========================================================================== */
CREATE ROLE IF NOT EXISTS R_TELECOM_ADMIN;
CREATE ROLE IF NOT EXISTS R_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS R_DATA_GOVERNANCE;
CREATE ROLE IF NOT EXISTS R_ANALYST_NORTH;
CREATE ROLE IF NOT EXISTS R_ANALYST_SOUTH;
CREATE ROLE IF NOT EXISTS R_ANALYST_GLOBAL;
CREATE ROLE IF NOT EXISTS R_COMPLIANCE_OFFICER;

GRANT ROLE R_DATA_ENGINEER      TO ROLE R_TELECOM_ADMIN;
GRANT ROLE R_DATA_GOVERNANCE    TO ROLE R_TELECOM_ADMIN;
GRANT ROLE R_ANALYST_GLOBAL     TO ROLE R_TELECOM_ADMIN;
GRANT ROLE R_COMPLIANCE_OFFICER TO ROLE R_TELECOM_ADMIN;
GRANT ROLE R_TELECOM_ADMIN      TO ROLE SYSADMIN;
GRANT ROLE R_TELECOM_ADMIN      TO ROLE LEAD_ROLE;

-- Warehouse usage grants
GRANT USAGE ON WAREHOUSE WH_INGEST    TO ROLE R_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_TRANSFORM TO ROLE R_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_BI        TO ROLE R_ANALYST_NORTH;
GRANT USAGE ON WAREHOUSE WH_BI        TO ROLE R_ANALYST_SOUTH;
GRANT USAGE ON WAREHOUSE WH_BI        TO ROLE R_ANALYST_GLOBAL;
GRANT USAGE ON WAREHOUSE WH_BI        TO ROLE R_COMPLIANCE_OFFICER;

-- Database/Schema usage
GRANT USAGE ON DATABASE RUNNING_TELCO TO ROLE R_DATA_ENGINEER;
GRANT USAGE ON DATABASE RUNNING_TELCO TO ROLE R_DATA_GOVERNANCE;
GRANT USAGE ON DATABASE RUNNING_TELCO TO ROLE R_ANALYST_NORTH;
GRANT USAGE ON DATABASE RUNNING_TELCO TO ROLE R_ANALYST_SOUTH;
GRANT USAGE ON DATABASE RUNNING_TELCO TO ROLE R_ANALYST_GLOBAL;
GRANT USAGE ON DATABASE RUNNING_TELCO TO ROLE R_COMPLIANCE_OFFICER;

GRANT USAGE ON SCHEMA RUNNING_TELCO.RAW           TO ROLE R_DATA_ENGINEER;
GRANT USAGE ON SCHEMA RUNNING_TELCO.STAGING       TO ROLE R_DATA_ENGINEER;
GRANT USAGE ON SCHEMA RUNNING_TELCO.CURATED       TO ROLE R_DATA_ENGINEER;
GRANT USAGE ON SCHEMA RUNNING_TELCO.CURATED       TO ROLE R_ANALYST_NORTH;
GRANT USAGE ON SCHEMA RUNNING_TELCO.CURATED       TO ROLE R_ANALYST_SOUTH;
GRANT USAGE ON SCHEMA RUNNING_TELCO.CURATED       TO ROLE R_ANALYST_GLOBAL;
GRANT USAGE ON SCHEMA RUNNING_TELCO.CURATED       TO ROLE R_COMPLIANCE_OFFICER;
GRANT USAGE ON SCHEMA RUNNING_TELCO.AUDIT_CTL     TO ROLE R_DATA_ENGINEER;
GRANT USAGE ON SCHEMA RUNNING_TELCO.ORCHESTRATION TO ROLE R_DATA_ENGINEER;
GRANT USAGE ON SCHEMA RUNNING_TELCO.GOVERNANCE    TO ROLE R_DATA_GOVERNANCE;
GRANT USAGE ON SCHEMA RUNNING_TELCO.GOVERNANCE    TO ROLE R_DATA_ENGINEER;
GRANT USAGE ON SCHEMA RUNNING_TELCO.SHARE_OUT     TO ROLE R_DATA_ENGINEER;

/* ==========================================================================
   CREATE-OBJECT PRIVILEGES
   ========================================================================== */
GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE PIPE,
      CREATE STREAM, CREATE PROCEDURE, CREATE FUNCTION, CREATE SEQUENCE
  ON SCHEMA RUNNING_TELCO.RAW TO ROLE R_DATA_ENGINEER;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE PIPE,
      CREATE STREAM, CREATE PROCEDURE, CREATE FUNCTION, CREATE SEQUENCE
  ON SCHEMA RUNNING_TELCO.STAGING TO ROLE R_DATA_ENGINEER;

GRANT CREATE TABLE, CREATE VIEW, CREATE FILE FORMAT, CREATE STAGE, CREATE PIPE,
      CREATE STREAM, CREATE PROCEDURE, CREATE FUNCTION, CREATE SEQUENCE
  ON SCHEMA RUNNING_TELCO.CURATED TO ROLE R_DATA_ENGINEER;

GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE SEQUENCE
  ON SCHEMA RUNNING_TELCO.AUDIT_CTL TO ROLE R_DATA_ENGINEER;

GRANT CREATE TASK ON SCHEMA RUNNING_TELCO.ORCHESTRATION TO ROLE R_DATA_ENGINEER;

GRANT CREATE TABLE, CREATE VIEW, CREATE PROCEDURE
  ON SCHEMA RUNNING_TELCO.SHARE_OUT TO ROLE R_DATA_ENGINEER;

GRANT CREATE TAG, CREATE MASKING POLICY, CREATE ROW ACCESS POLICY, CREATE TABLE
  ON SCHEMA RUNNING_TELCO.GOVERNANCE TO ROLE R_DATA_GOVERNANCE;

-- R_DATA_ENGINEER also needs CREATE STORAGE INTEGRATION (used in
-- 03_file_formats_stages.sql) and R_TELECOM_ADMIN needs CREATE SHARE
-- (used in 07_data_sharing) - both are ACCOUNT-level privileges, not
-- schema-level, so they're granted on the account. This requires
-- ACCOUNTADMIN (or a role already holding the privilege WITH GRANT OPTION)
-- to run - see README section "Deploying without ACCOUNTADMIN access" for
-- the alternative pattern if no ACCOUNTADMIN user is available in your
-- account.

--GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE R_DATA_ENGINEER;
--GRANT CREATE SHARE       ON ACCOUNT TO ROLE R_TELECOM_ADMIN;

-- Ownership for the pipeline service user (set at deploy time)
-- CREATE USER SVC_ETL_RUNNINGTELCO ...
-- GRANT ROLE R_DATA_ENGINEER TO USER SVC_ETL_RUNNINGTELCO;

